### ISSUE TITLE
Creare ed applicare texture della scuola di Atene

### ISSUE THREAD

**Issue by wbigger** [marconicivitavecchia/the-school-of-athens-vr#3]

**Comment by DavideSky** [comment]
https://github.com/marconicivitavecchia/the-school-of-athens-vr/commit/ec8841a10095cf8e2a8893940ead4ecdd6a365a5
!image https://user-images.githubusercontent.com/90967735/206033475-a03f2071-3665-4a39-81b3-f88f6645c31a.png

Aggiunta della texture del pavimento e del modello

**Comment by DavideSky** [comment]
https://github.com/marconicivitavecchia/the-school-of-athens-vr/commit/6b47b54b5e90b30e396f73be14b685ef870f3567
![V2](https://user-images.githubusercontent.com/90967735/207403811-326a04b1-1497-4acf-bbf8-607611acaefa.png)

**Comment by DavideSky** [comment]
https://github.com/marconicivitavecchia/the-school-of-athens-vr/commit/06378e5db2de89ab5d2b6a6d3b727a6e97dcfd09

![V3](https://user-images.githubusercontent.com/90967735/211401024-68c38446-dca6-4fd8-ac60-d6bccca4eed0.png)
