### ISSUE TITLE
Correggere gli errori di impaginazione della sceneggiatura della prima scena

### ISSUE THREAD

**Issue by wbigger** [marconicivitavecchia/the-school-of-athens-vr#43]
Nella sceneggiatura della prima scena ci sono alcune imprecisioni nell'impaginazione che vanno corretti per partire con l'implementazione.

**Comment by AleVillo** [comment]
https://docs.google.com/document/d/1tq9S7w1HqjIETMP6QBVwyHruWRiNP2pe0RO9-ZzUjkk/edit?usp=sharing

Ho corretto l'impaginazione e reso più scorrevole la lettura, sistemando quei piccoli errori che erano presenti lungo il copione.
Per quanto riguarda la ripetizione dell'evento del tablet, togliendolo o dalla seconda scena o dalla terza scena si perderebbe una parte sostanziosa di essa visto che occupa circa metà di entrambe: prima di modificare il copione ne parlerò con la prof. De Iorio.
