### ISSUE TITLE
Mesh del modello principale

### ISSUE THREAD

**Issue by DavideSky** [marconicivitavecchia/the-school-of-athens-vr#7]
#3 Stavo vedendo la mesh del modello principale e forse abbiamo un problema, perché è abbastanza pesante con 150.000/300.000 poligoni ed è fatto anche abbastanza male. Allego degli screenshot da blender:

![image](https://user-images.githubusercontent.com/90967735/198845852-997bed29-c303-4c37-bf64-b382d0863abc.png)
![image](https://user-images.githubusercontent.com/90967735/198845870-34f95765-8f40-4dcd-9825-9e7d232c1d92.png)
![image](https://user-images.githubusercontent.com/90967735/198845917-c47a92e0-fec2-4df8-b56d-e4e1e0afc951.png)

**Comment by DavideSky** [comment]
@wbigger lei che ne pensa?

**Comment by FThinker** [comment]
Oltre a semplificare la mesh, si potrebbe anche tagliare via alcune parti dell'edificio che non saranno visibili allo spettatore per risparmiare sul numero di poligoni. Che ne pensate?

**Comment by wbigger** [comment]
Personalmente credo che con un po' di lavoro su Blender si può sistemare a
sufficienza la mesh, e prima di tagliare parti andrebbe fatta una prova sul
visore per vedere le prestazioni.

Il sab 29 ott 2022, 20:30 FThinker ***@***.***> ha scritto:

**Comment by DavideSky** [comment]
a1eb989546bf98be5c1601c13504f579c1a84bb1 questo modello potrebbe essere già utilizzabile, andrebbe provato sul visore per vedere la performance

**Comment by wbigger** [comment]
Come facciamo per le prove? Prendete in prestito un Oculus o fate con gli
Alienware a scuola? Immagino bisogna essere fisicamente connessi con USB.

Il dom 20 nov 2022, 10:51 Davide Piccione ***@***.***> ha
scritto:

**Comment by DavideSky** [comment]
> 

Per le prove ci mettiamo d'accordo a scuola magari, perché non so di preciso come funziona per avviare un mondo in Unity da Oculus. Riguardo l'essere fisicamente connessi con l'USB penso che sia necessario, poiché in caso contrario non so da dove prenderebbe il mondo.

**Comment by wbigger** [comment]
Ho controllato, il modo migliore è in effetti connetterlo via USB, dovrebbe
essere una cosa semplice.

**Comment by DavideSky** [comment]
![V1](https://user-images.githubusercontent.com/90967735/203617329-15821cc1-566e-443f-b908-28f693eb8c6f.png)
Un primo render del modello

**Comment by DavideSky** [comment]
https://github.com/marconicivitavecchia/the-school-of-athens-vr/commit/7a42df4bdcea30f9961e2e335af34d30e9f74d75

**Comment by DavideSky** [comment]
https://github.com/marconicivitavecchia/the-school-of-athens-vr/commit/ec8841a10095cf8e2a8893940ead4ecdd6a365a5
![image](https://user-images.githubusercontent.com/90967735/206033475-a03f2071-3665-4a39-81b3-f88f6645c31a.png)
